# vim:set nowrap:
# vim:set syntax=sh:
goto init
echo This script only works with simh v4
exit

:init

set env DATE=%DATE_MM%/%DATE_DD%/79
set env TIME=%TIME_HH%:%TIME_MM%

set cpu api
set cpu xvm
set ttix lines=5
a ttix 2311
a rp0 xvmrsx_simh_kit/xvmrsx_rp02.dsk
l xvmrsx_simh_kit/rpboot.rim 77637
echo
echo To boot XVM/RSX, type "RSX" and press enter at the XVM/DOS "$" prompt.
echo To return to XVM/DOS, type "DOS" and press enter at the RSX MCR prompt.
echo To access the extra terminals, telnet to 127.0.0.1 on port 2311 and press Ctrl-T
echo to bring up the login prompt.
echo To log off MULTIACCESS, use the TDV command "OFF".
echo

noexpect
expect "ENTER DATE (MM/DD/YY)" send "%DATE%\r";c

run
