set cpu 11/20
set cpu 32K

set cr disabled
set xq disabled
set rk disabled
set hk disabled
set rha disabled
set tm disabled
set rx disabled
set rl disabled
set tq disabled
set dci disabled
set ke enabled
set rf 2p
set rf enabled
att rf s1s2unix_rf.img
set tc enabled
set tc locked
att tc s1.itp
set cpu history=1000

;set dci en
;set dci lines=8
;att dci 5555
set dco 7b

load m792low.load
dep system sr 173700
go 73700
