# vim:set nowrap:
# vim:set syntax=sh:
goto init
echo This script only works with simh v4
exit

:init

set env DATE=%DATE_MM%/%DATE_DD%/79
set env TIME=%TIME_HH%:%TIME_MM%

at rf dosv2a_4p.rf
load rfsboot.rim 77637
at -a ptr checkout.bt
at dt1 per.dta

noexpect
expect "ENTER DATE (MM/DD/YY)" send "%DATE%\r";c

go
